# Generated by Django 4.2.13 on 2026-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_dropoff_latitude_trip_dropoff_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rest_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
