# Generated by Django 6.0.5 on 2026-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_logsheet_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
