# Generated by Django 6.0.5 on 2026-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_actual_end_time_trip_actual_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystatus',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='dutystatus',
            index=models.Index(fields=['trip', 'start_time'], name='trips_dutys_trip_id_c0157d_idx'),
        ),
    ]
