# Generated by Django 6.0.5 on 2026-05-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_logsheet_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logsheet',
            new_name='trips_logsh_trip_id_0495b0_idx',
            old_name='trips_logsh_trip_id_date_idx',
        ),
    ]
